# Generated by Django 4.2.10 on 2024-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('student_id', models.IntegerField()),
                ('secured_student_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
