# Generated by Django 4.2.10 on 2024-02-26 17:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='teacher_create_course', to='user_profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=50)),
                ('num_of_lab', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('weight', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('lab_name', models.CharField(primary_key=True, serialize=False)),
                ('lab_type', models.CharField(choices=[('PreLab', 'Pre Lab'), ('InLab', 'In Lab'), ('PostLab', 'Post Lab')], max_length=50)),
                ('course_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course_semester')),
            ],
        ),
        migrations.CreateModel(
            name='Teaching_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Lecturer', 'Lecturer'), ('HeadLecturer', 'Head Lecturer'), ('TA', 'Teaching Assistant')], max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('course_semester', models.ManyToManyField(related_name='teaching_semester', to='courses.course_semester')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_name', models.CharField(max_length=255)),
                ('outcome_description', models.CharField(max_length=255)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='LabLOContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course_semester')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lab')),
                ('learning_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.learningoutcome')),
            ],
        ),
    ]
