# Generated by Django 4.2.10 on 2024-05-02 09:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(max_length=50, unique=True)),
                ('group', models.CharField(max_length=50, null=True)),
                ('num_of_lab', models.IntegerField()),
                ('role', models.CharField(choices=[('Lecturer', 'Lecturer'), ('HeadLecturer', 'Head Lecturer'), ('TA', 'Teaching Assistant')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50, null=True, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('creator', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exercise_code', models.CharField(max_length=50, null=True)),
                ('exercise_name', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('class_code', models.CharField()),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('lab_name', models.CharField(max_length=50, unique=True)),
                ('lab_type', models.CharField(choices=[('PreLab', 'Pre Lab'), ('InLab', 'In Lab'), ('PostLab', 'Post Lab')], max_length=50, null=True)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_class', to='courses.class')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_semestername', message='Semester must follow the format HK***', regex='^HK[0-9]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='UploadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binaries', models.FileField(upload_to='file_storage')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_submission', to='courses.class')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('time_taken', models.DurationField(null=True)),
                ('started_time', models.DateTimeField(null=True)),
                ('submitted_time', models.DateTimeField(null=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.exercise')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_outcome', models.CharField(blank=True, max_length=255)),
                ('outcome_code', models.CharField(max_length=50)),
                ('outcome_name', models.CharField(max_length=255)),
                ('outcome_description', models.CharField(blank=True, max_length=255)),
                ('threshold', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_course', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='LabLOContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_class', to='courses.class')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_lab', to='courses.lab')),
                ('outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_lo', to='courses.learningoutcome')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='lab_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lab'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='courses_cou_course__238746_idx'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_course', to='courses.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_semester', to='courses.semester'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
