# Generated by Django 4.1.13 on 2024-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
