# Generated by Django 4.2.10 on 2024-05-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='lab_name',
            new_name='lab',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='outcome_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
