# Generated by Django 4.2.10 on 2024-03-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('PreLab', 'Pre Lab'), ('InLab', 'In Lab'), ('PostLab', 'Post Lab')], max_length=50, null=True),
        ),
    ]
