# Generated by Django 4.2.10 on 2024-04-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lab_lab_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binaries', models.FileField(upload_to='submission_file')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_submission', to='courses.class')),
            ],
        ),
    ]
