# Generated by Django 4.2.10 on 2024-02-28 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_course_semester_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Lecturer', 'Lecturer'), ('HeadLecturer', 'Head Lecturer'), ('TA', 'Teaching Assistant')], max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Course_Semester',
            new_name='CourseSemester',
        ),
        migrations.DeleteModel(
            name='Teaching_Course',
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='course_semester',
            field=models.ManyToManyField(related_name='teaching_semester', to='courses.coursesemester'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
