# Generated by Django 4.2.10 on 2024-04-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='creater',
            new_name='creator',
        ),
    ]
