# Generated by Django 4.2.10 on 2024-03-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseteacher_rename_course_semester_coursesemester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteacher',
            name='course_semester',
            field=models.ManyToManyField(related_name='semester_teacher', to='courses.coursesemester'),
        ),
    ]
