# Generated by Django 4.2.10 on 2024-05-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(max_length=50),
        ),
    ]
