# Generated by Django 4.2.10 on 2024-04-28 04:17

import courses.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_creater_course_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=courses.models.get_submission_file_upload_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_class', to='courses.class')),
            ],
        ),
    ]
