# Generated by Django 4.2.10 on 2024-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_creater_course_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('student_id', models.IntegerField()),
                ('started_time', models.CharField(blank=True, max_length=100)),
                ('end_time', models.CharField(blank=True, max_length=100)),
                ('grade', models.FloatField()),
                ('question_id', models.IntegerField()),
            ],
        ),
    ]
