# Generated by Django 4.2.10 on 2024-03-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseteacher_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
