# Generated by Django 4.2.10 on 2024-05-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lab_lab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('question_id', 'class_code'), name='unique_question_class_combination'),
        ),
    ]
