# Generated by Django 4.2.10 on 2024-04-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_submissionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='courses.class'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
