# Generated by Django 4.2.10 on 2024-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_exercise_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='lab',
            constraint=models.UniqueConstraint(fields=('lab_name', 'class_code'), name='unique_lab_class_combination'),
        ),
    ]
