# Generated by Django 4.2.10 on 2024-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lab_lab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(blank=True, primary_key=True, serialize=False),
        ),
    ]
