# Generated by Django 4.2.10 on 2024-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_exercise_id_lab_unique_lab_class_combination'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='unique_question_class_combination',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='question_id',
            new_name='exercise_id',
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('exercise_id', 'class_code'), name='unique_question_class_combination'),
        ),
    ]
