# Generated by Django 4.2.10 on 2024-04-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_submissionfile_class_code_delete_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exercise_code', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('max_time', models.DurationField()),
                ('max_submit', models.IntegerField()),
                ('level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.learningoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_taken', models.DurationField()),
                ('started_time', models.DateTimeField()),
                ('submitted_time', models.DateTimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.exercise')),
            ],
        ),
    ]
