# Generated by Django 4.2.10 on 2024-05-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_exercise_unique_question_class_combination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='num_submit_file',
            field=models.IntegerField(default=0),
        ),
    ]
