# Generated by Django 4.2.10 on 2024-05-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_exercise_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='max_submit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='max_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
