# Generated by Django 4.2.10 on 2024-03-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lab_lab_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='courses_cou_course__238746_idx'),
        ),
    ]
