# Generated by Django 4.2.10 on 2024-05-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0008_class_num_submit_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_lab', to='courses.lab')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_outcome', to='courses.learningoutcome')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_student', to='students.student')),
            ],
        ),
    ]
