# Generated by Django 4.2.10 on 2024-06-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_outcomeprogress'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='unique_question_class_combination',
        ),
    ]
