# Generated by Django 4.2.10 on 2024-03-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_courses_cou_course__238746_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creater',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
