# Generated by Django 4.2.10 on 2024-03-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creater',
            field=models.EmailField(max_length=255),
        ),
    ]
