# Generated by Django 4.2.10 on 2024-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_exercise_unique_question_class_combination'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('exercise_id', 'class_code'), name='unique_question_class_combination'),
        ),
    ]
