# Generated by Django 4.2.10 on 2024-03-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacher',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
