# Generated by Django 4.2.10 on 2024-03-09 09:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_courseteacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lab',
            name='course_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesemester'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='lablocontribution',
            name='course_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesemester'),
        ),
        migrations.AlterField(
            model_name='lablocontribution',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lab'),
        ),
        migrations.AlterField(
            model_name='lablocontribution',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
