# Generated by Django 4.2.10 on 2024-03-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_course_code_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesemester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesemester_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseteacher_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='course_semester',
            field=models.ManyToManyField(related_name='courseteacher_semester', to='courses.coursesemester'),
        ),
    ]
