# Generated by Django 4.2.10 on 2024-03-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_coursesemester_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='outcome_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_course', to='courses.course'),
        ),
    ]
