# Generated by Django 4.2.10 on 2024-03-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_learningoutcome_outcome_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='outcome_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='learningoutcome',
            name='outcome_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
