# Generated by Django 4.2.10 on 2024-03-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_learningoutcome_outcome_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
