# Generated by Django 4.2.10 on 2024-03-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_lab_lab_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lablocontribution',
            name='learning_outcome',
        ),
        migrations.AddField(
            model_name='lablocontribution',
            name='outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_lo', to='courses.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='lablocontribution',
            name='course_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_semester', to='courses.coursesemester'),
        ),
        migrations.AlterField(
            model_name='lablocontribution',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_lab', to='courses.lab'),
        ),
    ]
