# Generated by Django 4.2.10 on 2024-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_head_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
